from .Searge_LLM_Node import *
from .Searge_DeepSeek_Node import NODE_CLASS_MAPPINGS as _DS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as _DS_DISPLAY_MAPPINGS

NODE_CLASS_MAPPINGS.update(_DS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(_DS_DISPLAY_MAPPINGS)
